export const ErrorCode = {
  INVALID_CITY: "INVALID_CITY",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  WEATHER_PROVIDER_UNAVAILABLE: "WEATHER_PROVIDER_UNAVAILABLE",
  WEATHER_PROVIDER_BAD_RESPONSE: "WEATHER_PROVIDER_BAD_RESPONSE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
